# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  git-push:
    desc: commits and pushes to github
    cmds:
      - git add .
      - git commit -m {{ .CLI_ARGS }}
      - git push -u origin main
  run-local:
    desc: run application with local.yaml
    cmds:
      - go run ./cmd/order/main.go --config="./config/local.yaml"
  default:
    desc: print list of commands
    cmds:
      - task --list
    silent: true
